/**
 * ─── Fittrybe — Sport Content Library ────────────────────────────────────────
 *
 * Static, SEO-optimised content for each sport. Powers /sports and
 * /sports/[sport] programmatic landing pages targeting "<sport> near me"
 * and related grassroots-discovery queries.
 *
 * Why static content here (not in Supabase):
 *  - Lets Next.js fully prerender at build time → fastest possible TTFB
 *  - Editorial copy doesn't change often; each entry should be hand-tuned
 *    for keyword intent, not autogenerated
 */

export interface SportContent {
  /** URL slug — must match SportId in events */
  slug: string;
  /** Display name */
  name: string;
  /** Used in social sharing */
  emoji: string;
  /** Short pitch (used in OG description and meta description) */
  tagline: string;
  /** Full intro paragraph for the landing page */
  intro: string;
  /** Long-tail SEO summary (~70-160 chars) — overrides tagline if set */
  metaDescription: string;
  /** H1-friendly headline */
  headline: string;
  /** Sub-keywords / related search terms (used in keywords array) */
  keywords: string[];
  /** Three "what you'll find" bullets */
  highlights: { title: string; body: string }[];
  /** Sport-specific FAQs — also serialised as FAQPage schema */
  faqs: { question: string; answer: string }[];
}

export const SPORTS: SportContent[] = [
  {
    slug: "football",
    name: "Football",
    emoji: "⚽",
    tagline:
      "Find casual football, five-a-side and seven-a-side games near you. Reserve your spot and meet your tribe.",
    intro:
      "Whether you call it football or soccer, Fittrybe makes it dead simple to find a kickabout near you. Browse five-a-side, seven-a-side and full-pitch sessions, see how many spots are left, and reserve in one tap.",
    metaDescription:
      "Find football games near you on Fittrybe. Five-a-side, seven-a-side and full-pitch grassroots sessions across the UK. Reserve your spot in one tap.",
    headline: "Find a Football Game Near You",
    keywords: [
      "football near me",
      "five-a-side football",
      "5-a-side football",
      "find football game",
      "casual football game",
      "grassroots football",
      "pickup football",
      "football session near me",
    ],
    highlights: [
      {
        title: "Five-a-side ready",
        body:
          "Most sessions are 5-a-side or 7-a-side at indoor or outdoor astro pitches.",
      },
      {
        title: "All abilities welcome",
        body:
          "Hosts mark sessions as Beginner, Casual or Competitive so you turn up to the right vibe.",
      },
      {
        title: "No team? No problem",
        body:
          "Join solo and you'll get split into balanced teams on arrival. Perfect for new movers.",
      },
    ],
    faqs: [
      {
        question: "How do I find a football game near me?",
        answer:
          "Open Fittrybe, allow location access, and filter by football. You'll see every upcoming session within reach — five-a-side, seven-a-side and full-pitch. Tap any session to view the venue and reserve a spot.",
      },
      {
        question: "Can I join a football session as a solo player?",
        answer:
          "Yes — most Fittrybe football sessions accept solo joiners and split players into balanced teams on arrival. It's the easiest way to play if you don't have a regular team.",
      },
      {
        question: "How much does a casual football game cost?",
        answer:
          "Five-a-side pitch hires typically split to £5–£10 per player. Each Fittrybe session shows the per-player price upfront so there are no surprises at the venue.",
      },
    ],
  },
  {
    slug: "basketball",
    name: "Basketball",
    emoji: "🏀",
    tagline:
      "Pickup basketball games and 3v3, 5v5 sessions near you — find a court, find a run, find your tribe.",
    intro:
      "From open runs to organised 5v5, Fittrybe surfaces every basketball session near you. See court details, skill level and remaining spots before you commit.",
    metaDescription:
      "Find basketball games and pickup runs near you on Fittrybe. 3v3, 5v5 and open-run sessions across the UK. Reserve a spot, show up, hoop.",
    headline: "Find a Basketball Run Near You",
    keywords: [
      "basketball near me",
      "pickup basketball",
      "5v5 basketball",
      "3v3 basketball",
      "find basketball game",
      "open run basketball",
      "basketball court near me",
    ],
    highlights: [
      {
        title: "Open runs daily",
        body: "Indoor halls and outdoor courts — see the next available run.",
      },
      {
        title: "Skill-matched",
        body: "Every host marks the level so beginners and hoopers find their lane.",
      },
      {
        title: "Court info upfront",
        body: "Hoop count, surface, parking — all visible before you reserve.",
      },
    ],
    faqs: [
      {
        question: "Where can I find pickup basketball games near me?",
        answer:
          "Fittrybe lists every nearby pickup run, organised 5v5 and 3v3 session. Filter by basketball, sort by distance, and reserve a spot in one tap.",
      },
      {
        question: "Can beginners play basketball on Fittrybe?",
        answer:
          "Absolutely. Hosts mark sessions as Beginner, Casual or Competitive so you can join the right level. Many runs explicitly welcome new players.",
      },
    ],
  },
  {
    slug: "tennis",
    name: "Tennis",
    emoji: "🎾",
    tagline:
      "Tennis matches, doubles sessions and friendly hits near you — court included.",
    intro:
      "Looking for a tennis partner without the hassle of booking apps and group chats? Fittrybe shows live tennis sessions near you with the court already booked. Singles, doubles and beginners' clinics.",
    metaDescription:
      "Find tennis partners and sessions near you on Fittrybe. Singles, doubles and friendly hits across UK courts. Reserve a spot in one tap.",
    headline: "Find a Tennis Session Near You",
    keywords: [
      "tennis near me",
      "tennis partner near me",
      "tennis session",
      "doubles tennis",
      "find tennis match",
      "tennis court near me",
    ],
    highlights: [
      {
        title: "Court already booked",
        body: "No need to share calendars — the host has the court sorted.",
      },
      {
        title: "Find a doubles partner",
        body: "Solo joiners are paired up automatically.",
      },
      {
        title: "Beginner clinics",
        body: "First-time? Look for sessions tagged Beginner or Open Hit.",
      },
    ],
    faqs: [
      {
        question: "How do I find a tennis partner near me?",
        answer:
          "Open Fittrybe, filter by tennis, and you'll see live doubles and singles sessions near you. Solo joiners are paired with other players automatically.",
      },
      {
        question: "Are the courts already booked?",
        answer:
          "Yes — every Fittrybe tennis session is hosted by someone who has the court secured. You just turn up and play.",
      },
    ],
  },
  {
    slug: "badminton",
    name: "Badminton",
    emoji: "🏸",
    tagline:
      "Badminton sessions, drop-ins and league nights near you — court and shuttles sorted.",
    intro:
      "Fittrybe makes weekly badminton drop-ins and league nights easy to discover. Pick a session, see the level, reserve and play.",
    metaDescription:
      "Find badminton sessions near you on Fittrybe. Drop-in nights, doubles play and club sessions across the UK. Reserve a spot in one tap.",
    headline: "Find a Badminton Session Near You",
    keywords: [
      "badminton near me",
      "badminton drop-in",
      "badminton club near me",
      "badminton session",
      "find badminton game",
      "doubles badminton",
    ],
    highlights: [
      {
        title: "Drop-in nights",
        body: "Weekly club sessions with rotating doubles — perfect for solo joiners.",
      },
      {
        title: "Skill-matched courts",
        body: "Beginners on one court, intermediates on another — no awkward mismatches.",
      },
      {
        title: "Equipment loans",
        body: "Many hosts loan racquets if you're new to the sport.",
      },
    ],
    faqs: [
      {
        question: "Where can I play badminton near me?",
        answer:
          "Fittrybe shows every public badminton drop-in, club night and casual session in your area. Filter by badminton and sort by distance to find one tonight.",
      },
      {
        question: "Do I need my own badminton racquet?",
        answer:
          "Not always — many host clubs loan racquets to new players. Check the session description before turning up to confirm.",
      },
    ],
  },
  {
    slug: "running",
    name: "Running",
    emoji: "🏃",
    tagline:
      "Running groups, 5K meetups and trail runs near you — pace yourself, with company.",
    intro:
      "Running solo gets old fast. Fittrybe surfaces local running clubs, 5K meetups, parkrun-style sessions and longer trail runs by pace and distance.",
    metaDescription:
      "Find running groups and meetups near you on Fittrybe. 5K social runs, club sessions and trail runs across the UK. Reserve a spot in one tap.",
    headline: "Find a Running Group Near You",
    keywords: [
      "running group near me",
      "running club near me",
      "5k near me",
      "running meetup",
      "trail running",
      "find running buddy",
    ],
    highlights: [
      {
        title: "Pace-grouped",
        body: "Each run lists the target pace so nobody gets dropped on day one.",
      },
      {
        title: "Solo-friendly",
        body: "Most groups have a meeting point and a 30-second \"who's new?\" intro.",
      },
      {
        title: "Distance options",
        body: "From 5K social loops to half-marathon long runs.",
      },
    ],
    faqs: [
      {
        question: "How do I find a running buddy or group near me?",
        answer:
          "Filter Fittrybe by running. You'll see every nearby session by pace, distance and start time. Reserve a spot, turn up and run.",
      },
      {
        question: "Are the running groups beginner-friendly?",
        answer:
          "Many are. Look for groups tagged Beginner or 5K social — these specifically pace for new runners and solo joiners.",
      },
    ],
  },
  {
    slug: "cycling",
    name: "Cycling",
    emoji: "🚴",
    tagline:
      "Group rides, social spins and weekend club rides near you — find your wheel.",
    intro:
      "From café spins to chaingang training rides, Fittrybe lists local cycling sessions by pace, distance and start point. Solo riders welcome.",
    metaDescription:
      "Find group rides and cycling clubs near you on Fittrybe. Social spins, café rides and training sessions across the UK.",
    headline: "Find a Group Ride Near You",
    keywords: [
      "cycling near me",
      "cycling group near me",
      "club ride",
      "group ride",
      "find cycling buddy",
      "social cycling",
    ],
    highlights: [
      {
        title: "Pace-graded rides",
        body: "Every ride lists target speed range — no-drop, social or chaingang.",
      },
      {
        title: "Café stops",
        body: "Most weekend rides include a café stop. Bring cash for a flat white.",
      },
      {
        title: "Solo-friendly",
        body: "Show up, introduce yourself, find your wheel.",
      },
    ],
    faqs: [
      {
        question: "How do I find a cycling group near me?",
        answer:
          "Filter Fittrybe by cycling. You'll see local club rides, social spins and training rides by pace and distance. Reserve a spot to confirm a place in the group.",
      },
      {
        question: "What pace do Fittrybe rides go at?",
        answer:
          "Each ride lists a target pace range. No-drop social rides are typically 25–28 km/h average; faster training rides 30–35 km/h+.",
      },
    ],
  },
  {
    slug: "swimming",
    name: "Swimming",
    emoji: "🏊",
    tagline:
      "Open-water swims, lane sessions and masters squads near you — pool sorted.",
    intro:
      "Fittrybe lists local swim sessions in pools, lakes and rivers. Lane swims, masters squads and supervised open-water meets — all in one place.",
    metaDescription:
      "Find swimming sessions and open-water swims near you on Fittrybe. Lane swims, masters squads and supervised meets across the UK.",
    headline: "Find a Swim Session Near You",
    keywords: [
      "swimming near me",
      "open water swimming",
      "masters swim",
      "lane swim",
      "swim meetup",
    ],
    highlights: [
      {
        title: "Lane swims & squads",
        body: "Pool sessions are listed by lane speed so you stay with your level.",
      },
      {
        title: "Open-water safety",
        body: "Outdoor swims are supervised — kayak escorts and bright caps included.",
      },
      {
        title: "Solo welcome",
        body: "Most swim sessions are solo-friendly — just turn up with kit.",
      },
    ],
    faqs: [
      {
        question: "Are the open-water swims supervised?",
        answer:
          "Yes — every Fittrybe open-water swim is hosted with safety cover (kayak or paddleboard escort) and pre-swim briefing.",
      },
    ],
  },
  {
    slug: "gym",
    name: "Gym",
    emoji: "🏋️",
    tagline:
      "Find a gym buddy, lifting partner or group HIIT class near you.",
    intro:
      "Training alone is fine. Training with a partner is better. Fittrybe lists gym buddy sessions, lifting meetups and group HIIT classes — bring some accountability to your week.",
    metaDescription:
      "Find a gym buddy, lifting partner or group HIIT class near you on Fittrybe. Train with people who turn up.",
    headline: "Find a Training Partner Near You",
    keywords: [
      "gym buddy near me",
      "lifting partner",
      "find gym partner",
      "group HIIT",
      "training partner near me",
    ],
    highlights: [
      {
        title: "Lift heavier, together",
        body: "Spotters and lifting partners on tap.",
      },
      {
        title: "Group HIIT classes",
        body: "Hosted bootcamps and small-group functional training.",
      },
      {
        title: "Accountability",
        body: "Reserve a spot — knowing someone is waiting beats a 6am snooze button.",
      },
    ],
    faqs: [
      {
        question: "Is Fittrybe just for organised classes?",
        answer:
          "No — many gym sessions are 1-on-1 lifting partner meetups. Anyone with a Fittrybe account can host or join.",
      },
    ],
  },
  {
    slug: "boxing",
    name: "Boxing",
    emoji: "🥊",
    tagline:
      "Boxing pads, sparring and white-collar training sessions near you.",
    intro:
      "From padwork pairs to gym-led sparring nights, Fittrybe makes boxing accessible without the intimidation. Hosts mark intensity so beginners and seasoned amateurs find their level.",
    metaDescription:
      "Find boxing pad sessions, sparring and group classes near you on Fittrybe. Beginner-friendly hosts across the UK.",
    headline: "Find a Boxing Session Near You",
    keywords: [
      "boxing near me",
      "boxing pads",
      "boxing class near me",
      "sparring near me",
      "white collar boxing",
    ],
    highlights: [
      {
        title: "Padwork pairs",
        body: "Bring a partner or get matched with another solo joiner.",
      },
      {
        title: "Beginner-safe sparring",
        body: "Light-touch only sessions clearly tagged.",
      },
      {
        title: "Equipment guidance",
        body: "Hosts list what to bring — most beginners can borrow gloves.",
      },
    ],
    faqs: [
      {
        question: "Can I try boxing as a beginner on Fittrybe?",
        answer:
          "Yes. Look for sessions tagged Beginner or Padwork — these are hosted to be welcoming to first-timers and solo joiners.",
      },
    ],
  },
];

export function getSportBySlug(slug: string): SportContent | undefined {
  return SPORTS.find((s) => s.slug === slug.toLowerCase());
}

export function getAllSportSlugs(): string[] {
  return SPORTS.map((s) => s.slug);
}
